pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                 bat(/gradlew clean build/)
            }
        }
        stage('startInLocal') {
            steps {
                //bat(/copy build\libs\discovery-0.0.1-SNAPSHOT.jar  D:\development\DEP\Deploy\discovery.jar/)
                withEnv(['JENKINS_NODE_COOKIE=dontkill']) {
                        bat(/start java -jar build\libs\oauthserver-0.0.1-SNAPSHOT.jar/)
                  }
            }
        } 
        stage('deployInServer'){
            steps {
                echo 'deploying'
            }
        }
    }
//     post {
//         success {
//             mail to: "XXXXX@gmail.com", subject:"SUCCESS: ${currentBuild.fullDisplayName}", body: "Build success"
//         }
//         failure {
//             mail to: "XXXXX@gmail.com", subject:"FAILURE: ${currentBuild.fullDisplayName}", body: "Boo, Build Failed failed."
//         }
//    }
}